import Head from 'next/head';

export default function Home() {
  return (
    <div className="container mx-auto px-10 md-8">
      <Head>
        <title>Bloxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}
